In [1]:
import torch
import numpy as np



In [3]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
data, x_data

([[1, 2], [3, 4]],
 tensor([[1, 2],
         [3, 4]]))

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
np_array, x_np

(array([[1, 2],
        [3, 4]]),
 tensor([[1, 2],
         [3, 4]]))

In [6]:
x_ones = torch.ones_like(x_data)
print(f"One Tensor:\n{x_ones}")

One Tensor:
tensor([[1, 1],
        [1, 1]])


In [7]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor:\n{x_rand}")

Random Tensor:
tensor([[0.8610, 0.7438],
        [0.4257, 0.9768]])


In [9]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor:\n{rand_tensor}")
print(f"Ones Tensor:\n{ones_tensor}")
print(f"Zeros Tensor:\n{ones_tensor}")

Random Tensor:
tensor([[0.4107, 0.5996, 0.7032],
        [0.2308, 0.6722, 0.5527]])
Ones Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [10]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor:{tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on:{tensor.device}")


Shape of tensor:torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on:cpu


In [12]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
tensor

tensor([[0.5180, 0.2293, 0.3368, 0.5758],
        [0.8530, 0.8432, 0.5282, 0.3252],
        [0.5437, 0.6352, 0.1677, 0.3187]], device='cuda:0')

In [ ]:
tensor = torch.ones(4, 4)
print()